Examples of types of cohesion and coupling
devblogs-ir/Modularization pull request #20
Opened 2023-12-24 10:58 UTC by arezookmn

2023-12-25 06:37 UTC, mohammadKarimi requested changes
Naming Conventions: please follow these rules. 
Your code is pretty, and complete. but I want you to fix some little issues then send UR PR again.

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Cohesion/LogicalCohesion/UserAuthenticationModule.cs
> +        private readonly List<User> registeredUsers;
naming Convention.
private field must be started with _ such as _registeredUsers.

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Cohesion/LogicalCohesion/UserAuthenticationModule.cs
> +            registeredUsers = new List<User>
now you can use collection expression in c#12

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Cohesion/LogicalCohesion/UserAuthenticationModule.cs
> +            if (user != null)
please use pattern matching, is not null

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Cohesion/SequentialCohesion/UserState.cs
> +namespace Cohesion.SequentialCohesion
please use File scoped namespace. 

namespace Cohesion.SequentialCohesion;

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Cohesion/SequentialCohesion/UserStateMachine.cs
> +        private UserState currentState;
Naming Conventions.

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Cohesion/SequentialCohesion/UserStateMachine.cs
> +        public UserState GetCurrentState()
For methods with single line , it is better to use lambda format. 
public UserState GetCurrentState()
    => currentState;

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Cohesion/TemporalCohesion/DailyWorkflow.cs
> +using System.Threading.Tasks;
Please Clean UR usings with ctrl+k+e in Visual studio.

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Coupling/CommonCoupling/RegistrationModule.cs
> +        public static void RegisterUser(string userName, string email)
in this code, I can not detect any Common Coupling.

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Coupling/CommonCoupling/RegistrationModule.cs
> +        public static void RegisterUser(string userName, string email)
username is one word. correct naming is username not userName.

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Coupling/CommonCoupling/RegistrationModule.cs
> +            int nextUserId = UserRepository.GetAllUsers().Count + 1;
in this line you might get NullPointerExceptions.

2023-12-25 06:37 UTC, mohammadKarimi commented on sources/Arezoo Kamane/Coupling/CommonCoupling/UserRepository.cs
> +        private static List<User> users = new List<User>();
yes, this example is a type of common coupling.

2023-12-25 11:45 UTC, arezookmn commented
Thanks for the comments 
I fixed those issues

2023-12-26 11:36 UTC, mohammadKarimi approved these changes
Perfect.

2023-12-26 11:37 UTC, merged